packages:
  - packages/*
  - themes/*
  - apps/*

catalog:
  '@tailwindcss/vite': ^4.3.3
  '@types/react': ^19.2.0
  '@types/react-dom': ^19.2.0
  eslint: ^10.11.0
  lucide: 1.47.0
  radix-ui: ^1.6.7
  react: ^19.3.0
  react-dom: ^19.3.0
  style-dictionary: ^5.5.5
  tailwind-variants: ^3.3.1
  tailwindcss: ^4.3.3
  tsdown: ^0.23.0
  typescript: ~6.0.0
  vitest: ^5.0.1
